apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: credentials-test
  namespace: external-secrets
spec:
  backendType: secretsManager # vault, akeyless, azureKeyVault, alicloudSecretsManager, gcpSecretsManager, ibmcloudSecretsManager
  dataFrom:
    - credentials-test
    - kv/extsec/secret1
  template:
    type: Opaque # kubernetes.io/dockerconfigjson, kubernetes.io/service-account-token
    metadata:
      annotations:
        userId: test-annotation
      labels:
        userId: test-label

