apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: credentials-test
  namespace: external-secrets
spec:
  backendType: secretsManager # vault, akeyless, azureKeyVault, alicloudSecretsManager, gcpSecretsManager, ibmcloudSecretsManager
  template:
    type: Opaque # kubernetes.io/dockerconfigjson, kubernetes.io/service-account-token
    metadata:
      annotations:
        userId: test-annotation
      labels:
        userId: test-label
  data:
    - key: credentials-test
      name: password
      property: password

